# Generated by Django 3.0.4 on 2020-05-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('author', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
