# Generated by Django 3.0.4 on 2020-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200508_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(blank='True', default='road.jpg', upload_to=''),
        ),
    ]
