# Generated by Django 3.0.4 on 2020-05-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumb',
        ),
    ]
